# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Simulate Poisson GLM reserve for different perturbed and excluded points.
#'
#' @param triangle Incremental claims triangle
#' @param sim_type Simulation type: `"single"` (the default), `"calender"`, or `"origin"`
#' @param n_boot Number of bootstrap simulations
#' @param factor Perturbation factor
#' @param boot_type Type of bootstrap: `"parametric"`, `"residuals"`, or `"pairs"`
#' @param sim_dist Distribution of process error: `"normal"` or `"gamma"`
#'
#' @details
#' The simulation configuration inputs `sim_type`, `factor`, `boot_type`,
NULL

#' Simulate Poisson GLM reserve.
#'
#' @param triangle Incremental claims triangle
#' @export
glmBoot <- function(triangle, n_boot, boot_type, opt, seed = 42L) {
    .Call('_claimsBoot_glmBoot', PACKAGE = 'claimsBoot', triangle, n_boot, boot_type, opt, seed)
}

#' @export
glmSim <- function(triangle, sim_type, n_boot, factors, boot_types, sim_dist = "normal", show_progress = TRUE, seed = 42L) {
    .Call('_claimsBoot_glmSim', PACKAGE = 'claimsBoot', triangle, sim_type, n_boot, factors, boot_types, sim_dist, show_progress, seed)
}

#' Simulate Mack CL reserve.
#'
#' @param triangle Cumulative claims triangle
#' @param n_boot Number of bootstrap simulations
#' @param boot_type Type of bootstrap: `"parametric"`, `"residuals"`, or `"pairs"`
#' @param proc_dist Distribution of process error: `"normal"`or `"gamma"`
#' @param cond Specified whether the bootstrap should be conditional or unconditional. Default is `TRUE`.
#' @export
mackBoot <- function(triangle, n_boot, boot_type, opt, cond, seed = 42L) {
    .Call('_claimsBoot_mackBoot', PACKAGE = 'claimsBoot', triangle, n_boot, boot_type, opt, cond, seed)
}

#' Simulate Mack CL reserve for different perturbed and excluded points.
#'
#' @param triangle Cumulative claims triangle
#' @param sim_type Simulation type: `"single"` (the default), `"calender"`, or `"origin"`
#' @param n_boot Number of bootstrap simulations
#' @param factor Perturbation factor
#' @param boot_type Type of bootstrap: `"parametric"`, `"residuals"`, or `"pairs"`
#' @param proc_dist Distribution of process error: `"normal"` or `"gamma"`
#' @param cond Specified whether the bootstrap should be conditional or unconditional. Default is `TRUE`.
#'
#' @details The simulation configuration inputs `sim_type`, `factor`, `boot_type`, `proc_dist` and `conditional` can be either strings or character vectors. In the latter case, the simulation is computed for all feasible combinations.
#' @export
mackSim <- function(triangle, sim_type, n_boot, mean_factors, sd_factors, boot_types, sim_dist = "normal", show_progress = TRUE, seed = 42L) {
    .Call('_claimsBoot_mackSim', PACKAGE = 'claimsBoot', triangle, sim_type, n_boot, mean_factors, sd_factors, boot_types, sim_dist, show_progress, seed)
}

test_pois <- function(n, lambda) {
    .Call('_claimsBoot_test_pois', PACKAGE = 'claimsBoot', n, lambda)
}

