# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Leading NA
#' 
#' This function returns a logical vector identifying if 
#' there are leading NA, marking the leadings NA as TRUE and
#' everything else as FALSE.
#'
#' @param x An integer vector
#' @export
mackBoot <- function(triangle, n_boot, resids_type, boot_type, dist) {
    .Call('_patternBreak_mack_boot', PACKAGE = 'patternBreak', triangle, n_boot, resids_type, boot_type, dist)
}

#' Leading NA
#' 
#' This function returns a logical vector identifying if 
#' there are leading NA, marking the leadings NA as TRUE and
#' everything else as FALSE.
#'
#' @param x An integer vector
#' @export
glmBoot <- function(triangle, n_boot) {
    .Call('_patternBreak_glm_boot', PACKAGE = 'patternBreak', triangle, n_boot)
}

#' Leading NA
#' 
#' This function returns a logical vector identifying if 
#' there are leading NA, marking the leadings NA as TRUE and
#' everything else as FALSE.
#'
#' @param x An integer vector
#' @export
.mackSim <- function(triangle, n_boot, config, type) {
    .Call('_patternBreak_mack_sim', PACKAGE = 'patternBreak', triangle, n_boot, config, type)
}

#' Leading NA
#' 
#' This function returns a logical vector identifying if 
#' there are leading NA, marking the leadings NA as TRUE and
#' everything else as FALSE.
#'
#' @param x An integer vector
#' @export
.glmSim <- function(triangle, n_boot, config, type) {
    .Call('_patternBreak_glm_sim', PACKAGE = 'patternBreak', triangle, n_boot, config, type)
}

