# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Leading NA
#' 
#' This function returns a logical vector identifying if 
#' there are leading NA, marking the leadings NA as TRUE and
#' everything else as FALSE.
#'
#' @param x An integer vector
#' @export
.glmBoot <- function(triangle, n_boot) {
    .Call('_patternBreak_glm_boot', PACKAGE = 'patternBreak', triangle, n_boot)
}

#' Leading NA
#' 
#' This function returns a logical vector identifying if 
#' there are leading NA, marking the leadings NA as TRUE and
#' everything else as FALSE.
#'
#' @param x An integer vector
#' @export
.glmSim <- function(triangle, n_boot, config, type) {
    .Call('_patternBreak_glm_sim', PACKAGE = 'patternBreak', triangle, n_boot, config, type)
}

#' Simulate Mack CL reserve.
#'
#' @param triangle Cumulative claims triangle
#' @export
mackBoot <- function(triangle, n_boot, boot_type, process_dist, conditional, resids_type) {
    .Call('_patternBreak_mackBoot', PACKAGE = 'patternBreak', triangle, n_boot, boot_type, process_dist, conditional, resids_type)
}

#' Simulate Mack CL reserve for different perturbed and excluded points.
#'
#' @param triangle Cumulative claims triangle
#' @param sim_type Simulation type: `"single"` (the default), `"calender"`, or `"origin"`
#' @param n_boot Number of bootstrap simulations
#' @param factors Vector of perturbation factors
#' @param boot_type Type of bootstrap: `"parametric"`, `"non-parametric"`, or `"pairs"`
#' @param process_dist Distribution of process error: `"normal"` or `"gamma"`
#' @param conditional Specified whether the bootstrap should be conditional or unconditional. Default is `TRUE`.
#' @export
mackSim <- function(triangle, sim_type, n_boot, factors, boot_type, process_dist, conditional = TRUE, resids_type = "none", show_progress = TRUE) {
    .Call('_patternBreak_mackSim', PACKAGE = 'patternBreak', triangle, sim_type, n_boot, factors, boot_type, process_dist, conditional, resids_type, show_progress)
}

validate_rng <- function(n_samples) {
    .Call('_patternBreak_validate_rng', PACKAGE = 'patternBreak', n_samples)
}

test_pois <- function(n, lambda) {
    .Call('_patternBreak_test_pois', PACKAGE = 'patternBreak', n, lambda)
}

