# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Simulate Poisson GLM reserve.
#'
#' @param triangle Incremental claims triangle
#' @export
glm_boot <- function(triangle, n_boot) {
    .Call('_patternBreak_glm_boot', PACKAGE = 'patternBreak', triangle, n_boot)
}

#' Simulate Poisson GLM reserve for different perturbed and excluded points.
#'
#' @param triangle Incremental claims triangle
#' @param sim_type Simulation type: `"single"` (the default), `"calender"`, or `"origin"`
#' @param n_boot Number of bootstrap simulations
#' @param factor Perturbation factor
#' @param boot_type Type of bootstrap: `"parametric"`, `"residuals"`, or `"pairs"`
#' @param proc_dist Distribution of process error: `"normal"` or `"gamma"`
#' @param cond Specified whether the bootstrap should be conditional or unconditional. Default is `TRUE`.
#'
#' @details
#' The simulation configuration inputs `sim_type`, `factor`, `boot_type`, `proc_dist` and `conditional` can be
#' either strings or character vectors. In the latter case, the simulation is computed for all feasible combinations.
#' @export
glm_sim <- function(triangle, n_boot, config, type) {
    .Call('_patternBreak_glm_sim', PACKAGE = 'patternBreak', triangle, n_boot, config, type)
}

mackBoot <- function(triangle, n_boot, boot_types, proc_dist, conditional, resids_type = NULL, seed = 42L) {
    .Call('_patternBreak_mackBoot', PACKAGE = 'patternBreak', triangle, n_boot, boot_types, proc_dist, conditional, resids_type, seed)
}

mackSim <- function(triangle, sim_type, n_boot, mean_factors, sd_factors, boot_types, sim_dist = "normal", show_progress = TRUE, seed = 42L) {
    .Call('_patternBreak_mackSim', PACKAGE = 'patternBreak', triangle, sim_type, n_boot, mean_factors, sd_factors, boot_types, sim_dist, show_progress, seed)
}

test_pois <- function(n, lambda) {
    .Call('_patternBreak_test_pois', PACKAGE = 'patternBreak', n, lambda)
}

